version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DATABASE_URL: "postgresql+asyncpg://myuser:mypassword@db:5432/mydb"
      SECRET_KEY: "gfdmhghif38yrf9ew0jkf32"
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
